import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const contents = `// Generated by scripts/write-version.mjs — do not edit by hand.\nexport const VETCH_VERSION = ${JSON.stringify(pkg.version)};\n`;
writeFileSync(join(root, "src/version.ts"), contents);
